apiVersion: apps/v1
kind: Deployment
metadata:
  name: cosas-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cosas
  template:
    metadata:
      labels:
        app: cosas
    spec:
      containers:
        - name: cosas
          image: cosas
          imagePullPolicy: Never
          env:
          - name: PORT
            value: "3000"
          - name: MONGO_HOST
            value: "cosas-mongo-srv"
          - name: MONGO_PORT
            value: "27017"
          - name: NATS_HOST
            value: "nats-srv"
          - name: NATS_PORT
            value: "4222"      

---
apiVersion: v1
kind: Service
metadata:
  name: cosas-srv
spec:
  selector:
    app: cosas
  ports:
    - name: cosas
      protocol: TCP
      port: 3000
      targetPort: 3000
