apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: nodeco.local
      http:
        paths:
          - path: /api/buscador/.*
            pathType: Prefix
            backend:
              service:
                name: buscador-srv
                port:
                  number: 3000  
          - path: /api/cosas/.*
            pathType: Prefix
            backend:
              service:
                name: cosas-srv
                port:
                  number: 3000 